basic_app/urls.py
from django.conf.urls import url
from basic_app import views
from django.contrib import admin

app_name = 'basic_app'

urlpatterns = [
    url(r'^$', views.index, name ='index'),
    url(r'^profile-amr/$', views.profile, name='amr'),
    url(r'^profile-duygu/$', views.profile, name='duygu'),
    url(r'^profile-harrison/$', views.profile, name='harrison'),
    url(r'^profile-pierre/$', views.profile, name='pierre'),
    url(r'^profile-robert/$', views.profile, name='robert'),
    url(r'^profile-robert/$', views.profile, name='robert'),
   
   
    # url(r'^signup/$', views.users, name='signup'),
    url(r'^contact/', views.form1, name="contact"),
    url(r'^admin/',admin.site.urls),
    
]

experience_app/urls.py
from django.conf.urls import url
from experience_app import views

app_name = 'experience_app'

urlpatterns = [
    url(r'^experience/', views.experience, name ='experience'),
]

fun_portfolio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name ='index'),   
    url(r'^basic_app/', include('basic_app.urls')), 
    url(r'^experience_app/', include('experience_app.urls')),       
    url(r'^subscribe/$', views.subscribe, name='subscribe'),
]
    
    

basic_app/models.py
#from django.core.mail import message
from django.db import models

# Create your models here.
from django.db import models

class Subscribers(models.Model):

    email = models.EmailField(unique=True, null=False)
class Users(models.Model):
    name = models.CharField(max_length= 255)
    email = models.EmailField()
    message = models.TextField()
    
    def __str__(self):
        return self.email

experience_app/models.py
from django.db import models

# Create your models here.

basic_app/forms.py
from django import forms
from basic_app.models import Subscribers

class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribers
        fields = '__all__'


from django.forms import fields
from .models import Users


class ContactForm(forms.Form):
    class meta:
        model = Users
        fields ='_all_'
    
    

basic_app/views.py
from django.shortcuts import render
from django.contrib import messages
from basic_app.forms import SubscribeForm
from django import forms
from basic_app import forms
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.core.mail import message, send_mail, BadHeaderError
from django.http import HttpResponse
from .models import Users

# Create your views here.
def index(request):
    return render(request, 'index.html')

def profile(request):
    str_req = str(request)    
    if 'amr' in str_req:
        title = 'Amr'
    elif 'duygu' in str_req:
        title = 'Duygu'
    elif 'harrison' in str_req:
        title = 'Harrison'
    elif 'pierre' in str_req:
        title = 'Pierre'
    elif 'robert' in str_req:
        title = 'Robert'
    else:
        title = str_req
    return render(request, 'profile.html', {'title':title})


def subscribe(request):
    
    form = SubscribeForm()
    if request.method == 'POST':
        form = SubscribeForm(request.POST) 
        if form.is_valid():
            print("Email:" + form.cleaned_data['email'])
            form.save(commit=True) 
            messages.success(request,"Subscription successfully completed!")
        else:
             messages.success(request,"Invalid email adress!") #success just for css
        return render(request, 'index.html')
        
def form1(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
#if the user requests to send a form, this checks if the form is valid
     
        if form.is_valid():
            print("Validation success")
            
        if request.POST.get('name')and request.POST.get('email') and request.POST.get('message'):
            pst=Users()
                 
            pst.name = request.POST.get('name')
            pst.email = request.POST.get('email')
            pst.message = request.POST.get('message')
            pst.save()
            form = ContactForm()
           
    return render(request, 'contact.html')
        
        
       
            
           
    

experience_app/views.py
from django.shortcuts import render


# Create your views here.
def experience(request):
    return render(request, 'experience.html')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
        <!-- Google Fonts Roboto -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"/>
        <!-- MDB   (buttons looks better)  @Duygu --> 
        <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"/>
        <title></title>
    </head>
    <body>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <nav class="navbar navbar-expand-lg py-3 navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a href="{% url 'index' %}" class="navbar-brand">
                    <img src="https://bootstrapious.com/i/snippets/sn-nav-logo/logo.png" width="45" alt="" class="d-inline-block align-middle mr-2">
                    <span class="text-uppercase font-weight-bold">Professional Profile</span>
                </a>
                <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span class="navbar-dark navbar-toggler-icon"></span></button>

                <div id="navbarSupportedContent" class="collapse navbar-collapse">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
                        <li class="nav-item"><a class="nav-link" href="">Services</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'experience_app:experience' %}">Experience</a></li>
                        <li class="nav-item"><a class="nav-link" href="">Projects</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:contact' %}">Contact</a></li>
                    </ul>
                </div>    
            </div>
        </nav>

        <div class="container">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li {% if message.tags %} class = '{{ message.tags }}' {% endif %}>{{ message}}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            
            {% block body_block %}

            {% endblock %}
        </div>

        <footer class="text-center text-lg-start border border-white mt-xl-5 pt-4 bg-dark shadow-sm">
            <section class="mb-4 bg-dark p-4">
                <!-- Facebook -->
                <a class="btn btn-outline-light btn-floating m-1" href="https://www.facebook.com/" target="_blank" role="button"><i class="fab fa-facebook-f"></i></a>
                <!-- Twitter -->
                <a class="btn btn-outline-light btn-floating m-1" href="https://www.twitter.com/home" target="_blank" role="button"><i class="fab fa-twitter"></i></a>
                <!-- Google -->
                <a class="btn btn-outline-light btn-floating m-1" href="https://www.google.com" target="_blank" role="button"><i class="fab fa-google"></i></a>
                <!-- Instagram -->
                <a class="btn btn-outline-light btn-floating m-1" href="https://www.instagram.com/" target="_blank" role="button"><i class="fab fa-instagram"></i></a>
                <!-- Linkedin -->
                <a class="btn btn-outline-light btn-floating m-1" href="https://www.linkedin.com/" target="_blank" role="button"><i class="fab fa-linkedin-in"></i></a>
                <!-- Github -->
                <a class="btn btn-outline-light btn-floating m-1" href="https://www.github.com/" target="_blank" role="button"><i class="fab fa-github"></i></a>
            </section>
            <div class="container p-4">
                <div class="row" >
                    <div class="col-sm-6">
                        <h5 class="text-uppercase mb-4">Sign up to our newsletter</h5>
                    </div>
                    <div class="col-sm-6">
                        <form action="{% url 'subscribe' %}" method="post">
                            {% csrf_token %}
                            <input type="email" name="email" class="form-control" placeholder="Your Email ID Please" required>
                            <br>
                            <input type="submit" value="Subscribe" class="btn btn-outline-light">
                        </form>
                    </div>
                </div>
            </div>
            <div class="text-center p-3 border-top border-white">
                © 2021 Copyright
            </div>
        </footer>   
    </body>
</html>

templates/contact.html
<!--Contact form-->
{% extends 'base.html' %}
{% block body_block %}

<!--div style = "margin:8opx"-->
 

<div class="container">
 
 {% load crispy_forms_tags %}  
<h1>Contact</h1>
<h4> please send us a message </h4>


            
    <form action="" method = "POST">
      {% csrf_token %}
      <div class="form-group">
      <label for="exampleFormControlInput1">Name</label>
      <input name="name" type="text" class="form-control" id="exampleFormControlInput1" placeholder="Your name...">
      </div>

      <div class="form-group">
        <label for="exampleFormControlInput1">E-mail</label>
        <input name="email" type="email" class="form-control" id="exampleFormControlInput1" placeholder="Your email address...">
      </div>

      <div class="form-group">
        <label for="exampleFormControlTextarea1">Message</label>
        <textarea name="message" class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="What's on your mind..."></textarea>
      </div>
       
      
        
        
          
        {{form.as_p|crispy}}
    
      <input type="submit" class = "btn btn-primary" value ="submit"/>
    
    </form>
    </div>

    {% endblock %}

templates/experience.html
{% extends 'base.html' %}
{% block body_block %}

<!-- title and tag -->
<div class="container">
    <h1>The First Project of Team 4</h1>
    <hr>

    <!-- Content of the body-->
    <h2>Experience</h2>
    <!--<div class="row"> -->
    <main>
        <table>
            <thead>
                <tr>
                    <th>Developer Image</th>
                    <th>Name</th>
                    <th>Experience</th>
                    <th>Skills</th>
                    <th>Education</th>
                </tr>
            </thead>
            <tr>
                <td><img src="/static/images/developer.png" alt="Developer 1"></td>
                <td>Duygu</td>
                <td>
                    <div class="left">
                        <ul>
                            <li>Organized transition from invoice to Quickbooks and online invoicing.</li>
                            <li>Utilized sci-kit learn in Python to simulate possible outcomes under different scenarios
                                that the user chose</li>                            
                        </ul>
                    </div>
                </td>
                <div class="skill">
                <td>PHP / Oracle / SQL / HTML / C# / Photoshop</td>
            </div>
                <td> B.S. WEB DEVELOPMENT</td>
            </tr>

            <tr>
                <td><img src="/static/images/developer.png" alt="Developer 2"></td>
                <td>Harrison</td>
                <td>
                    <div class="left">
                        <ul>
                            <li>Trained over 50 staff members in internal web functions, including steps on how to
                                independently make minor updates and changes</li>
                            <li>Built the logic for a streamlined ad-serving platform that scaled to our 100M users
                                which improved the page speed by 14% after implementation</li>
                        </ul>
                    </div>
                </td>
                <td>Oracle / JavaScript / HTML / CSS / .NET / C#</td>
                <td>B.S. WEB DEVELOPMENT</td>
            </tr>
            <tr>
                <td><img src="/static/images/developer.png" alt="Developer 3"></td>
                <td>Amr Ibn El Ahrache</td>
                <td>
                    <div class="left">
                        <ul>
                            <li>Trained 3 administrative assistants on customer service.</li>
                            <li>Built the logic for a streamlined ad-serving platform that scaled to our 100M users
                                which improved the page speed by 14% after implementation</li>
                        </ul>
                    </div>
                </td>
                <td>PERL / SQL / JavaScript / HTML / CSS / .NET</td>
                <td>B.S. WEB DEVELOPMENT / CERTIFIED JAVA PROGRAMMER</td>
            </tr>
            <tr>
                <td><img src="/static/images/developer.png" alt="Developer 4"></td>
                <td>Robert Andersson</td>
                <td>
                    <div class="left">
                        <ul>
                            <li>Trained over 50 staff members in internal web functions, including steps on how to
                                independently make minor updates and changes</li>
                            <li>Utilized sci-kit learn in Python to simulate possible outcomes under different scenarios
                                that the user chose</li>
                        </ul>
                    </div>
                </td>
                <td>PHP / Oracle / SQL / HTML / CSS / C#</td>
                <td>A.A. PROGRAMMING / B.S. WEB DEVELOPMENT</td>
            </tr>
            <tr>
                <td><img src="/static/images/developer.png" alt="Developer 5"></td>
                <td>Pierre</td>
                <td>
                    <div class="left">
                        <ul>
                            <li>Trained over 50 staff members in internal web functions, including steps on how to
                                independently make minor updates and changes</li>
                            <li>Built the logic for a streamlined ad-serving platform that scaled to our 100M users
                                which improved the page speed by 14% after implementation</li>
                        </ul>
                    </div>
                </td>
                <td>JavaScript / HTML / CSS / .NET / C#</td>
                <td>CERTIFIED JAVA PROGRAMMER</td>
            </tr>
        </table>
    </main>

    <!-- </div> -->
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body_block %}

<!-- title and tag -->
<div class="container">
    <h1>The First Project of Team 4</h1>
    <hr>
    <!-- Carousel @Duygu-->
      <div class="bd-example">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="../static/images/home_image.jpg" class="d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
                <h5>First slide label</h5>
                <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
              </div>
            </div>
            <div class="carousel-item">
              <img src="../static/images/home_image.jpg" class="d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
                <h5>Second slide label</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
              </div>
            </div>
            <div class="carousel-item">
              <img src="../static/images/home_image.jpg" class="d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
                <h5>Third slide label</h5>
                <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="false"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>

    <!-- Content of the body-->
    <br>
    <h2>Our team members</h2>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-12 col-md-6">
          <div class="card">
              <img src="../static/images/profile.jpg" class="card-img-top" alt="...">
              <div class="card-body">
                  <h3>
                      <a href="{% url 'basic_app:amr' %}">Amr</a>
                  </h3>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
          </div>  
        </div>
        <div class="col-12 col-md-6">  
          <div class="card">
              <img src="../static/images/profile.jpg" class="card-img-top" alt="...">
              <div class="card-body">
                  <h3>
                      <a href="{% url 'basic_app:duygu' %}">Duygu</a>
                  </h3>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
          </div>
        </div> 
      </div>  
      <div class="row align-items-center">  
        <div class="col-12 col-md-6">
          <div class="card">
              <img src="../static/images/profile.jpg" class="card-img-top" alt="...">
              <div class="card-body">
                  <h3>
                      <a href="{% url 'basic_app:harrison' %}">Harrison</a>
                  </h3>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
          </div> 
        </div>
        <div class="col-12 col-md-6">
          <div class="card">
              <img src="../static/images/profile.jpg" class="card-img-top" alt="...">
              <div class="card-body">
                  <h3>
                      <a href="{% url 'basic_app:pierre' %}">Pierre</a>
                  </h3>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
          </div>  
        </div>
      </div>  
      <div class="row align-items-center">  
        <div class="col-12 col-md-6">  
          <div class="card">
              <img src="../static/images/profile.jpg" class="card-img-top" alt="...">
              <div class="card-body">
                  <h3>
                      <a href="{% url 'basic_app:robert' %}">Robert</a>
                  </h3>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
          </div>
        </div> 
        <div class="col-12 col-md-6">
          <div class="card">
              <img src="../static/images/group.jpg" class="card-img-top" alt="...">
              <div class="card-body">
                  <h3>
                      <a href="#">Our projects</a>
                  </h3>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
          </div> 
        </div>  
      </div>
  </div>
</div>
{% endblock %}

templates/index_old.html
{% extends 'base.html' %}
{% block body_block %}

<!-- title and tag -->
<div class="container">
    <h1>The First Project of Team 4</h1>
    <hr>

    <!-- Content of the body-->
    <h2>Portfolio</h2>
    <div class="row">
        <div class="column">
            <div class="content">
                <img src="https://www.geeksforgeeks.org/wp-content/uploads/html.png"
                    alt="" style="width:100%">
                <h3>
                    <a href="#">HTML Tutorials</a>
                </h3>
                 <p>
                    HTML stands for Hyper Text Markup
                    Language. It is used to design web
                    pages using markup language. HTML
                    is the combination of Hypertext and
                    Markup language. Hypertext defines
                    the link between the web pages.
                </p>
            </div>
        </div>
        
        <div class="column">
            <div class="content">
                <img src="https://www.geeksforgeeks.org/wp-content/uploads/CSS.png"
                    alt="" style="width:100%">
                <h3>
                    <a href="#">CSS Tutorials</a>
                </h3>
                <p>
                    Cascading Style Sheets, fondly referred
                    to as CSS, is a simply designed language
                    intended to simplify the process of
                    making web pages presentable. CSS allows
                    you to apply styles to web pages.
                </p>
            </div>
        </div>
        
        <div class="column">
            <div class="content">
                <img src="https://www.geeksforgeeks.org/wp-content/uploads/javascript.png"
                    alt="" style="width:100%">
                <h3>
                    <a href="#">JavaScript Tutorials</a>
                </h3>
                <p>
                    Javascript was developed by Brendan
                    Eich in 1995. At first, it was called
                    LiveScript but was later name to
                    JavaScript. JavaScript is the muscle
                    of the structure
                </p>
            </div>
        </div>

        <div class="column">
            <div class="content">
                <img src="https://media.geeksforgeeks.org/wp-content/cdn-uploads/20200711122552/Python-Programming-Language.png"
                    alt="" style="width:100%">
                <h3>
                    <a href="#">Python Tutorials</a>
                </h3>
                <p>
                    Python is a programming language that 
                    lets you work more quickly and integrate 
                    your systems more effectively. Installing 
                    Python is generally easy, and nowadays many 
                    Linux and UNIX distributions include a recent Python. 
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container">
    <h1 class="display-4">Hello, My name is {{ title }} !</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action" aria-current="true">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Project 1</h5>
            <small>155.251 likes</small>
          </div>
          <p class="mb-1">
            Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius
            blandit.
          </p>
          <small>Donec id elit non mi porta.</small>
        </a>
        <a href="#" class="list-group-item list-group-item-action">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Project 2</h5>
            <small class="text-muted">285.123 likes</small>
          </div>
          <p class="mb-1">
            Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius
            blandit.
          </p>
          <small class="text-muted">Donec id elit non mi porta.</small>
        </a>
        <a href="#" class="list-group-item list-group-item-action">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Project 3</h5>
            <small class="text-muted">87.265 likes</small>
          </div>
          <p class="mb-1">
            Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius
            blandit.
          </p>
          <small class="text-muted">Donec id elit non mi porta.</small>
        </a>
    </div>
</div>
{% endblock %}